#!/usr/bin/env bash
set -euo pipefail

image=localhost/aeons-actions-runner:2.337.0-1
if podman image exists "$image"; then
    exit 0
fi

podman build \
    --dns=1.1.1.1 \
    --dns=9.9.9.9 \
    --pull=missing \
    --tag "$image" \
    --file /usr/share/aeons-runner-image/Containerfile \
    /usr/share/aeons-runner-image
